repository = "https://github.com/longbridge/gpui-kit"
revision = "0f0ab35233212f8f3277028995caf0c41e13ee6c"
version = "0.5.1"
archive = "https://crates.io/api/v1/crates/gpui-component/0.5.1/download"
sha256 = "d021d46b4088d3d93a57ccdf443da85695a77272108caca2f6fe5369f584966a"
patch = "patches/gpui-component/0001-pinned-gpui-compatibility.patch"
